Update Slack Link to signup page
nautobot/nautobot pull request #1856
Opened 2022-06-06 17:45 UTC by itdependsnetworks

# Closes: N/A
# What's Changed

Simple signup link documentation change.

# TODO
- [ ] Explanation of Change(s)

2022-06-06 17:45 UTC, itdependsnetworks commented
I do not think the current link makes sense. The user will not have anything to do from that link, since there is a chicken & egg problem.

2022-06-07 03:33 UTC, bryanculver commented on README.md
> +Questions? Comments? Start by perusing our [GitHub discussions](https://github.com/nautobot/nautobot/discussions) for the topic you have in mind, or <a href="https://slack.networktocode.com/">join th
This is a markdown file, not HTML.

2022-06-07 03:33 UTC, bryanculver commented on nautobot/docs/docker/index.md
> +Nautobot is packaged as a Docker image for use in a production environment. The published image is based on the `python:3.7-slim` image to maintain the most compatibility with Nautobot deployments. T
Please change link to Markdown format.

2022-06-07 03:34 UTC, bryanculver requested changes
Please fix link formats.

2022-06-07 17:43 UTC, bryanculver commented on nautobot/core/templates/500.html
> +                            If further assistance is required, please <a href="https://slack.networktocode.com/">join the **#nautobot**</a> Slack #nautobot channel on Network to Code's Slack communit
```suggestion
                            If further assistance is required, please <a href="https://slack.networktocode.com/">join the <b>#nautobot</b></a> channel on Network to Code's Slack community and post your question.
```

2022-06-07 17:43 UTC, bryanculver commented on README.md
> +Questions? Comments? Start by perusing our [GitHub discussions](https://github.com/nautobot/nautobot/discussions) for the topic you have in mind, or [join the **#nautobot**](https://slack.networktoco
```suggestion
Questions? Comments? Start by perusing our [GitHub discussions](https://github.com/nautobot/nautobot/discussions) for the topic you have in mind, or [join the **#nautobot**](https://slack.networktocode.com/) channel on Network to Code Slack community!
```

2022-06-07 17:43 UTC, bryanculver commented on nautobot/docs/docker/index.md
> +Nautobot is packaged as a Docker image for use in a production environment. The published image is based on the `python:3.7-slim` image to maintain the most compatibility with Nautobot deployments. T
```suggestion
Nautobot is packaged as a Docker image for use in a production environment. The published image is based on the `python:3.7-slim` image to maintain the most compatibility with Nautobot deployments. The Docker image and deployment strategies are being actively developed, check back here or [join the **#nautobot**](https://slack.networktocode.com/) channel on the Network to Code Slack community for the most up to date information.
```

2022-06-07 17:47 UTC, bryanculver commented
Suggested the same call to action on all three spots:

> ...join the [#nautobot](https://slack.networktocode.com/) channel on Network to Code's Slack community...

I think the link should still be on "Network to Code's Slack community" and not "#nautobot" because they have to join the community first before joining the channel. Thoughts?

2022-06-08 02:31 UTC, merged