Fix wrong icon displayed
nautobot/nautobot pull request #1863
Opened 2022-06-08 18:17 UTC by timizuoebideri1

# Closes: #1750 
# What's Changed

# TODO

- [ ] Explanation of Change(s)
- [ ] Attached Screenshots, Payload Example
- [ ] Unit, Integration Tests
- [ ] Documentation Updates (when adding/changing features)
- [ ] Example Plugin Updates (when adding/changing features)
- [ ] Outline Remaining Work, Constraints from Design

2022-06-08 18:50 UTC, briddo requested changes
LGTM but I noticed other incorrect calls of `render_boolean` in the codebase. Can we add the fixes to this PR plz? Boolean arguments should be Python boolean values (True/False) in all cases. Occurrences images attached..

![Screenshot 2022-06-08 at 19 42 31](https://user-images.githubusercontent.com/655255/172693745-acaac952-3a3d-4ca2-b48a-c18b65347208.png)
![Screenshot 2022-06-08 at 19 40 18](https://user-images.githubusercontent.com/655255/172693752-c4d152ee-61a2-4643-9377-381b4761d801.png)

2022-06-09 16:38 UTC, briddo approved these changes

2022-06-09 16:39 UTC, briddo approved these changes
LGTM

2022-06-09 16:58 UTC, glennmatthews approved these changes

2022-06-13 13:19 UTC, merged