2185 filter panel UI, add button to expand/collapse the search panel
nautobot/nautobot pull request #2187
Opened 2022-08-11 19:09 UTC by Dav-C

# Closes: #<2185>
# Add a filter button that collapses and expands the search panel. This button only appears if { filter_form } context has been provided.

# TODO

- [X] Explanation of Change(s)
- [X] Attached Screenshots, Payload Example
- [ ] Unit, Integration Tests
- [ ] Documentation Updates (when adding/changing features)
- [ ] Example Plugin Updates (when adding/changing features)
- [ ] Outline Remaining Work, Constraints from Desig
![image1](https://user-images.githubusercontent.com/57967713/184219765-1dc07e4f-e668-48bf-9bbc-be24c608c0d9.jpg)
![image2](https://user-images.githubusercontent.com/57967713/184219768-1f8a0d9c-5e57-43cc-a849-d583b351250f.jpg)

2022-08-11 20:43 UTC, bryanculver requested changes
I'm curious how this plays into #1998

2022-08-11 20:43 UTC, bryanculver commented on nautobot/core/templates/generic/object_list.html
> +    {% if request.user.is_authenticated and filter_form %}
```suggestion
    {% if filter_form %}
```

2022-08-11 22:37 UTC, Dav-C reviewed
I included request.user.is_authenticated to maintain parity with the config button, but I see its not really necessary.

2022-08-18 20:36 UTC, Dav-C commented
Due to some upcoming UI changes, I'll close this PR for now and revisit after the next release.

2022-08-18 20:36 UTC, closed without merging