Augment `get_route_for_model()` to support REST API routes.
nautobot/nautobot pull request #2223
Opened 2022-08-16 23:18 UTC by jathanism

# Closes: #DNE
# What's Changed
- This adds an `api=True` argument to `nautobot.utilities.utils.get_route_for_model`
- Expanded the Development Best Practices guide with a section on "Getting URL Routes"

# TODO

- [ ] Explanation of Change(s)
- [ ] Attached Screenshots, Payload Example
- [ ] Unit, Integration Tests
- [ ] Documentation Updates (when adding/changing features)
- [ ] Example Plugin Updates (when adding/changing features)
- [ ] Outline Remaining Work, Constraints from Design

2022-08-17 14:27 UTC, glennmatthews reviewed
I think there's also a case in `nautobot.utilities.views.GetReturnURLMixin.get_return_url` that could perhaps also use `get_route_for_model`?

2022-08-17 14:27 UTC, glennmatthews commented on nautobot/docs/development/best-practices.md
> +    The first argument may also optionally be an instance of a model, or may be substituted a with string using the dotted notation of `{app_label}:{model}` (e.g. `dcim.device`).
```suggestion
    The first argument may also optionally be an instance of a model, or a string using the dotted notation of `{app_label}.{model}` (e.g. `dcim.device`).
```

2022-08-17 14:27 UTC, glennmatthews commented on nautobot/utilities/utils.py
> +        "plugins-api:example_plugin-api:examplemodel-list"
```suggestion
        "plugins-api:example_plugin-api:examplemodel-list"
        >>> get_route_for_model("dcim.site", "list")
        "dcim:site_list"
        >>> get_route_for_model("dcim.site", "list", api=True)
        "dcim-api:site-list"
```

2022-09-09 13:05 UTC, glennmatthews commented
@jathanism What's needed to move this out of draft status?

2022-09-09 16:00 UTC, bryanculver requested changes
Let's get this buttoned up and passing tests to simplify some other PRs.

If we miss a few of the old-style calls that's fine but getting the method available will help continued drift from say #2348 & #2371

2022-09-14 16:54 UTC, glennmatthews commented on nautobot/docs/development/best-practices.md
> +
Can we add a note here that API view support was added in 1.4.3?

2022-09-14 16:54 UTC, glennmatthews commented on nautobot/docs/development/best-practices.md
> +## UI Routes
```suggestion
### UI Routes
```

2022-09-14 19:14 UTC, bryanculver approved these changes
:shipit:

2022-09-14 19:15 UTC, merged