Resolves #2552 - Issues with footer CSS on resizing of page
nautobot/nautobot pull request #2553
Opened 2022-10-02 16:55 UTC by whitej6

# Closes: #2552 
# What's Changed

Update CSS to to better account for footer resizing.

# TODO

- [ ] Explanation of Change(s)
- [ ] Attached Screenshots, Payload Example
- [ ] Unit, Integration Tests
- [ ] Documentation Updates (when adding/changing features)
- [ ] Example Plugin Updates (when adding/changing features)
- [ ] Outline Remaining Work, Constraints from Design

2022-10-11 15:32 UTC, whitej6 commented
Static sizing was causing the overflow issue.

2022-10-11 17:14 UTC, bryanculver requested changes

2022-10-11 17:14 UTC, bryanculver commented on nautobot/project-static/css/base.css
> -}
We either need to keep `.push` or update styling for `BANNER_BOTTOM`:

New appearance
<img width="1167" alt="Screen Shot 2022-10-11 at 13 10 28" src="https://user-images.githubusercontent.com/31187/195156774-63a869e6-7e95-4353-a6ca-7cff4011e679.png">

Previous appearance
<img width="1125" alt="Screen Shot 2022-10-11 at 13 12 16" src="https://user-images.githubusercontent.com/31187/195156885-69bc8e5b-b7ec-4f7b-b594-48036e411a5f.png">

2022-11-04 16:07 UTC, bryanculver approved these changes

2022-11-04 16:28 UTC, jathanism approved these changes

2022-11-04 17:09 UTC, merged