Add more detail to the README
nautobot/nautobot pull request #2599
Opened 2022-10-09 16:29 UTC by Santhusha-bit

Added more detail to the synopsis section at the top of the README which may make it easier for developers to understand Nautobot

2022-10-11 18:54 UTC, bryanculver requested changes

2022-10-11 18:54 UTC, bryanculver commented on README.md
> -Nautobot is a Network Source of Truth and Network Automation Platform.
I thinks the reformatting here isn't entirely helpful.

But @nautobot/core could we consider moving the fork portion of this down to the footer, something like:

```md
<!--(the rest of the README.md file)-->

---
## Notices

> Nautobot was initially developed as a fork of NetBox (v2.10.4).  NetBox was originally developed by Jeremy Stretch at DigitalOcean and the NetBox Community. 

```

2022-10-11 18:54 UTC, bryanculver commented on README.md
> -
We'd actually like to keep the screenshots but move them to GIFs (another open backlog item, see: #2589).

2022-10-11 18:54 UTC, bryanculver commented on README.md
> +### Nautobot enables 3 key use cases.
I think `## Key Use Cases` here is sufficient.
```suggestion
```

2022-10-11 18:54 UTC, bryanculver commented on README.md
> +3. Platform for Network Automation Apps - The Nautobot plugin system enables users to create Network Automation Apps. Apps can be as lightweight or robust as needed based on user needs. Using Nautobo
👍 taking a page from the docs homepage. Can you bolden the use case titles as styled in the docs?

2022-10-12 06:32 UTC, Santhusha-bit commented
@bryanculver Waiting for your feedback

2022-10-12 17:27 UTC, Santhusha-bit commented
Done @bryanculver

2022-10-26 10:29 UTC, bryanculver commented
@Santhusha-bit Please resolve the markdownlint issue: https://github.com/nautobot/nautobot/actions/runs/3236622066/jobs/5392840607

2022-10-31 14:44 UTC, bryanculver approved these changes

2022-10-31 20:18 UTC, merged