Read only issue 2477
nautobot/nautobot pull request #2600
Opened 2022-10-10 11:04 UTC by gneville-ot

# Closes: #2477
# What's Changed

- Changes the Docker Entrypoint so it runs `nautobot-server collectstatic` if `NAUTOBOT_DOCKER_SKIP_INIT=True`, this is needed so static content can be served when standing up in maintenance mode.
- Allows for easier overriding of the SESSION_ENGINE default with ENVVAR `NAUTOBOT_SESSION_ENGINE`, this is changed when standing up in maintenance mode.

# TODO

- [X] Explanation of Change(s)
- [X] Added change log fragment(s) (for more information see [the documentation](https://docs.nautobot.com/projects/core/en/stable/development/#creating-changelog-fragments))
- [ ] Attached Screenshots, Payload Example
- [ ] Unit, Integration Tests
- [X] Documentation Updates (when adding/changing features)
- [ ] Example Plugin Updates (when adding/changing features)
- [ ] Outline Remaining Work, Constraints from Design

2022-10-18 19:32 UTC, jathanism commented
Thanks for this submission! Sorry we didn't get to it for the 1.4.~6~7 release.

2022-10-18 19:51 UTC, glennmatthews reviewed
Thank you!

2022-10-18 19:51 UTC, glennmatthews commented on nautobot/core/templates/nautobot_config.py.j2
> +
Can this be implemented in `nautobot/core/settings.py` instead? (See also #2578)

2022-10-20 10:40 UTC, gneville-ot commented
Hi @jathanism, @glennmatthews ,

I've moved the setting in to `nautobot/core/settings.py` and tested and still works.

Thanks

2022-10-20 17:18 UTC, jathanism commented
@nniehoff Can you please give this a look!

2022-10-20 19:20 UTC, nniehoff requested changes
This makes sense in this case, however we definitely have use cases we need to account for where we don't want to run collectstatic either.  We need to account for these.

2022-10-24 11:16 UTC, gneville-ot commented
Hi @nniehoff,

As a regular user of nautobot I won't know all of these use cases. 
As I see it now, `collectstatic` always runs if you're spinning up with docker and doesn't if you set `NAUTOBOT_DOCKER_SKIP_INIT=True`. Is there any reason not to run `collectstatic` when setting  `NAUTOBOT_DOCKER_SKIP_INIT=True`?

I won't be able to progress this PR without feedback from you.

2022-10-24 13:53 UTC, nniehoff commented
@gneville-ot that's exactly what I am saying there are use cases out there where when `NAUTOBOT_DOCKER_SKIP_INIT=True` we truly do mean skip all initialization to include `collectstatic`.  Mainly these are around where we use shared file systems for static such as S3.  Nearly all of the HA deployments we do are active/active deployments of Nautobot with active/active HA postgres behind them.  I'm sorry for the trailblazing you are having to do with this issue.  For this PR I'd like to see some other options maybe if `NAUTOBOT_DOCKER_SKIP_INIT=True`  we have a number of other variables to address all of the components of `post_upgrade` which can be found [here](https://github.com/nautobot/nautobot/blob/develop/nautobot/core/management/commands/post_upgrade.py#L76-L114)

2022-11-22 13:53 UTC, glennmatthews requested changes
Nick's concerns need to be addressed. I agree that we probably need to keep `NAUTOBOT_DOCKER_SKIP_INIT` as meaning "skip all init tasks" and instead add a different (set of) variables that get passed through to the `nautobot-server post_upgrade` command so that we can for example run `post_upgrade --no-migrate --no-clearsessions --no-remove-stale-contenttypes --no-trace-paths --no-invalidate-all` if it's desirable to only run `collectstatic`... looking at that complexity, maybe we could consider adding a `--only` option to the `post_upgrade` command (`nautobot-server post_upgrade --only collectstatic`)?

2022-12-02 15:41 UTC, bryanculver commented
Pending feedback: https://github.com/nautobot/nautobot/issues/2477#issuecomment-1329703574

2023-05-11 12:11 UTC, bryanculver commented
Closing as this largely needs to be broken out into its own two issues that this doesn't fully address:
- We have a larger need around what maintenance mode does and does not support, see #3183
- Based on @glennmatthews' comment above we could have a few more knobs for the Docker entryfile to tune what commands get run on startup instead of an all-or-nothing post_upgrade. The use case here is just one of several but there is no simple way to "override" the entryfile without drift management, see #3733

2023-05-11 12:11 UTC, closed without merging