Update contributing docs link
nautobot/nautobot pull request #2614
Opened 2022-10-13 15:52 UTC by chadell

# Closes: no issue opened
# What's Changed
The documentation link was broken

# TODO

- [ ] Explanation of Change(s)
- [ ] Added change log fragment(s) (for more information see [the documentation](https://docs.nautobot.com/projects/core/en/stable/development/#creating-changelog-fragments))
- [ ] Attached Screenshots, Payload Example
- [ ] Unit, Integration Tests
- [ ] Documentation Updates (when adding/changing features)
- [ ] Example Plugin Updates (when adding/changing features)
- [ ] Outline Remaining Work, Constraints from Design

2022-10-13 21:32 UTC, gsnider2195 commented on changes/2614.fixed
> +Fixed CONTRIBUTING.md link to actual Nautobot documentation
```suggestion
Fixed CONTRIBUTING.md link to actual Nautobot documentation.
```

2022-10-13 21:34 UTC, gsnider2195 requested changes
Just a minor nitpick on the changelog fragment. Thanks @chadell for fixing this!

2022-10-14 13:08 UTC, gsnider2195 approved these changes

2022-10-14 14:37 UTC, glennmatthews approved these changes

2022-10-17 20:42 UTC, merged