Docs status updates - Fixes #150
nautobot/nautobot pull request #268
Opened 2021-04-08 23:55 UTC by scetron

### Fixes: #150

Fixes any references to the status field and places a reference to the new status model into the documentation.

2021-04-09 02:26 UTC, itdependsnetworks commented on nautobot/docs/models/circuits/circuit.md
> +Each circuit must also assigned one of the following operational [`statuses`](https://nautobot.readthedocs.io/en/latest/models/extras/status/):
```suggestion
Each circuit must be assigned to a status, the following [`statuses`](https://nautobot.readthedocs.io/en/latest/models/extras/status/) are provided by default.
```

2021-04-09 02:28 UTC, itdependsnetworks commented on nautobot/docs/models/ipam/vlan.md
> +Each VLAN must be assigned one of the following operational [`statuses`](https://nautobot.readthedocs.io/en/latest/models/extras/status/):
```suggestion
Each VLAN ust be assigned to a status, the following [`statuses`](https://nautobot.readthedocs.io/en/latest/models/extras/status/) are provided by default:
```

2021-04-09 13:11 UTC, scetron commented on nautobot/docs/models/ipam/vlan.md
> +Each VLAN must be assigned one of the following operational [`statuses`](https://nautobot.readthedocs.io/en/latest/models/extras/status/):
Fixed.

2021-04-09 13:12 UTC, scetron commented on nautobot/docs/models/circuits/circuit.md
> +Each circuit must also assigned one of the following operational [`statuses`](https://nautobot.readthedocs.io/en/latest/models/extras/status/):
Fixed

2021-04-09 16:00 UTC, scetron commented
I will fix where there are absolute links that should be relative links. (outside of /nautobot/)

2021-04-09 16:59 UTC, jathanism requested changes
Thank you for this update! Nitpicked the heck out of this just for consistency and clarity.

2021-04-09 16:59 UTC, jathanism commented on nautobot/docs/models/dcim/cable.md
> +Each cable may be assigned a type, label, length, and color. Each cable must also assigned one of three operational [`statuses`](https://nautobot.readthedocs.io/en/latest/models/extras/status/):
```suggestion
Each cable may be assigned a type, label, length, and color. Each cable must also assigned to an operational [`status`](https://nautobot.readthedocs.io/en/latest/models/extras/status/). The following statuses are available by default:
```

2021-04-09 16:59 UTC, jathanism commented on nautobot/docs/models/dcim/powerfeed.md
> +Each power feed is assigned an operational type (primary or redundant) and one of the following [`statuses`](https://nautobot.readthedocs.io/en/latest/models/extras/status/):
```suggestion
Each power feed is assigned an operational type (primary or redundant) and a [`status`](https://nautobot.readthedocs.io/en/latest/models/extras/status/). The following statuses are available by default:
```

2021-04-09 16:59 UTC, jathanism commented on nautobot/docs/models/dcim/rack.md
> +Similarly, each rack must be assigned an operational [`statuses`](https://nautobot.readthedocs.io/en/latest/models/extras/status/):
```suggestion
Similarly, each rack must be assigned an operational [`status`](https://nautobot.readthedocs.io/en/latest/models/extras/status/):
```

2021-04-09 16:59 UTC, jathanism commented on nautobot/docs/models/dcim/site.md
> +Each site must be assigned a unique name and may optionally be assigned to a region and/or tenant. The following operational [`statuses`](https://nautobot.readthedocs.io/en/latest/models/extras/statu
```suggestion
Each site must be assigned a unique name and operational [`status`](https://nautobot.readthedocs.io/en/latest/models/extras/status/) and may optionally be assigned to a region and/or tenant. The following statuses are available by default:
```

2021-04-09 16:59 UTC, jathanism commented on nautobot/docs/models/ipam/ipaddress.md
> +Each IP address can also be assigned an operational status and a functional role. Default status options are provided, including the following, but may be customized as with any other "status" field
```suggestion
Each IP address can also be assigned an operational [status](https://nautobot.readthedocs.io/en/latest/models/extras/status/) and a functional role. The following statuses are available by default:
```

2021-04-09 16:59 UTC, jathanism commented on nautobot/docs/models/circuits/circuit.md
> +Status fields can now be customized via the new [`status`](https://nautobot.readthedocs.io/en/latest/models/extras/status/) model.
IMO just remove this since it's redundant with the link above it.

2021-04-09 16:59 UTC, jathanism commented on nautobot/docs/models/dcim/cable.md
> +Status fields can now be customized via the new [`status`](https://nautobot.readthedocs.io/en/latest/models/extras/status/) model.
Same: IMO just remove this since it's redundant with the link above it.

2021-04-09 16:59 UTC, jathanism commented on nautobot/docs/models/dcim/powerfeed.md
> +Status fields can now be customized via the new [`status`](https://nautobot.readthedocs.io/en/latest/models/extras/status/) model.
Same: IMO just remove this since it's redundant with the link above it.

2021-04-09 16:59 UTC, jathanism commented on nautobot/docs/models/dcim/rack.md
> +Status fields can now be customized via the new [`status`](https://nautobot.readthedocs.io/en/latest/models/extras/status/) model.
Same: IMO just remove this since it's redundant with the link above it.

2021-04-09 16:59 UTC, jathanism commented on nautobot/docs/models/dcim/site.md
> +Status fields can now be customized via the new [`status`](https://nautobot.readthedocs.io/en/latest/models/extras/status/) model.
Same: IMO just remove this since it's redundant with the link above it.

2021-04-09 16:59 UTC, jathanism commented on nautobot/docs/models/ipam/prefix.md
> +Each prefix must be assigned a status and can optionally be assigned a role. These terms are often used interchangeably so it's important to recognize the difference between them. The **status** defi
```suggestion
Each prefix must be assigned a [status](https://nautobot.readthedocs.io/en/latest/models/extras/status/) and can optionally be assigned a role. These terms are often used interchangeably so it's important to recognize the difference between them. The **status** defines a prefix's operational state. The following statuses are available by default:
```

2021-04-09 16:59 UTC, jathanism commented on nautobot/docs/models/ipam/vlan.md
> +Each VLAN must be assigned a status, the following [`statuses`](https://nautobot.readthedocs.io/en/latest/models/extras/status/) are available by default:
```suggestion
Each VLAN must be assigned a [`status`](https://nautobot.readthedocs.io/en/latest/models/extras/status/). The following statuses are available by default:
```

2021-04-09 16:59 UTC, jathanism commented on nautobot/docs/models/ipam/vlan.md
> +Status fields can now be customized via the new [`status`](https://nautobot.readthedocs.io/en/latest/models/extras/status/) model.
Same: IMO just remove this since it's redundant with the link above it.

2021-04-09 16:59 UTC, jathanism commented on nautobot/docs/models/virtualization/virtualmachine.md
> +Status fields can now be customized via the new [`status`](https://nautobot.readthedocs.io/en/latest/models/extras/status/) model.
Same: IMO just remove this since it's redundant with the link above it.

2021-04-09 16:59 UTC, jathanism commented on nautobot/docs/models/virtualization/virtualmachine.md
> +Like devices, each VM can be assigned a platform and/or functional role, and must have one of the following operational [`statuses`](https://nautobot.readthedocs.io/en/latest/models/extras/status/) a
```suggestion
Like devices, each VM can be assigned a platform and/or functional role, and an operational [`status`](https://nautobot.readthedocs.io/en/latest/models/extras/status/). The following statuses are available by default:
```

2021-04-12 21:11 UTC, jathanism approved these changes
Good to go! I only have this one suggestion to align w/ the Nova terminology your example.

2021-04-12 21:11 UTC, jathanism commented on nautobot/docs/models/extras/status.md
> +For Virtual Machines, if utilizing OpenStack, statuses in Nautobot could be customized to reflect the specific ['statuses available to Nova VMs'](https://docs.openstack.org/nova/latest/reference/vm-s
```suggestion
For Virtual Machines, if utilizing OpenStack, statuses in Nautobot could be customized to reflect the specific [Nova virtual machine states](https://docs.openstack.org/nova/latest/reference/vm-states.html).
```

2021-04-13 21:46 UTC, jathanism commented
@scetron Can you please force push to your branch to get the tests to re-run so we can get this merged? Thanks.

2021-04-14 14:59 UTC, merged