feat: #3184 add Git to mandatory dependencies.
nautobot/nautobot pull request #3186
Opened 2023-01-30 07:48 UTC by DimasInchidi

# Closes: #3184
# What's Changed
Installation instruction in documentation

# TODO
This might not the fix wanted for #3184 but it's necessary for new developer as long as the error exists. thus, further discussion might be needed.

2023-01-31 14:55 UTC, bryanculver commented
Thanks for the PR @DimasInchidi! Mind adding a changelog fragment for #3184: https://docs.nautobot.com/projects/core/en/stable/development/#creating-changelog-fragments

2023-01-31 14:55 UTC, bryanculver requested changes
Missing changelog fragment

2023-02-01 16:59 UTC, bryanculver commented on nautobot/docs/installation/index.md
> +| Git        | Additional   | 2.19            |
```suggestion
| Git        | Additional   | 2.0            |
```

Any version 2.0+ should suffice.

2023-02-14 19:22 UTC, gsnider2195 commented on nautobot/docs/installation/index.md
> +| Git        | Additional   | 2.0            |
```suggestion
| Git        | Additional   | 2.0             |
```

2023-02-14 19:22 UTC, gsnider2195 approved these changes

2023-02-15 00:07 UTC, merged