Merge branch 'develop' of https://github.com/nautobot/nautobot into develop
nautobot/nautobot pull request #3381
Opened 2023-03-01 15:31 UTC by egenius01

# Closes: #<ISSUE NUMBER GOES HERE>
# What's Changed

# TODO

- [ ] Explanation of Change(s)
- [ ] Added change log fragment(s) (for more information see [the documentation](https://docs.nautobot.com/projects/core/en/stable/development/#creating-changelog-fragments))
- [ ] Attached Screenshots, Payload Example
- [ ] Unit, Integration Tests
- [ ] Documentation Updates (when adding/changing features)
- [ ] Example Plugin Updates (when adding/changing features)
- [ ] Outline Remaining Work, Constraints from Design

2023-03-01 18:25 UTC, bryanculver requested changes
There is some cleanup that should be done with regard to commented-out code and functions that do nothing.

Also, please update the PR description with the planned/desired use cases for these changes.

2023-03-01 18:25 UTC, bryanculver commented on nautobot/users/tests/test_filters.py
> +
It seems this function serves no purpose.

2023-03-01 18:25 UTC, bryanculver commented on nautobot/users/filters.py
> +            "has_changes",
If you have the field defined above it is not needed here. This section is for "magic" filters that introspect fields on the given model and provide determined proper filter and lookup expression combinations.

2023-03-05 04:02 UTC, egenius01 commented on nautobot/users/filters.py
> +            # "has_logentry_set",
Alright i'd do that, Thanks

2023-03-05 07:06 UTC, closed without merging