Model Driven SSO Configuration POC
nautobot/nautobot pull request #3543
Opened 2023-04-05 19:52 UTC by whitej6

This is a really old piece of work and is by no means ready for review. Wanted to submit the PR as a jumping off point on using database objects and/or constant config to back SSO configuration.

2023-04-08 19:15 UTC, jathanism requested changes

2023-04-08 19:15 UTC, jathanism commented on nautobot/core/settings.py
> +CONSTANCE_MANAGE_SSO = is_truthy(os.getenv("NAUTOBOT_CONSTANCE_MANAGE_SSO", False))
Terse docstring here please.

2023-04-08 19:15 UTC, jathanism commented on nautobot/core/settings_funcs.py
> +            pass
Would it be possible for you you use [`django.utils.module_loading.import_string`](https://docs.djangoproject.com/en/4.1/ref/utils/#django.utils.module_loading.import_string) here instead? It does this already but with less code.

We also have [`nautobot.extras.plugin.utils.import_object`](https://github.com/nautobot/nautobot/blob/develop/nautobot/extras/plugins/utils.py#L19), but I hate that it lives inside of `plugin.utils`...

2023-04-08 19:15 UTC, jathanism commented on nautobot/core/sso.py
> +    """Subclassing to allow for constance config exposed via Nautobot."""
Can you please revise this docstring to describe how it is used? It's not clear act a `Strategy` is.

2023-04-08 19:15 UTC, jathanism commented on nautobot/core/sso.py
> +        """Force text on URL named settings that are instance of Promise."""
Why would we want to do this?

2023-04-08 19:15 UTC, jathanism commented on nautobot/users/admin.py
> +    form = SSOBackendAdminForm
Is there really a need for a custom form? The fields can limited in the `ModelAdmin`.
```suggestion


@admin.register(SSOBackend)
class SSOBackendAdmin(NautobotModelAdmin):
    fields = ["name", "backend", "enabled", "configuration"]
```

2023-04-08 19:15 UTC, jathanism commented on nautobot/users/models.py
> +BACKEND_CHOICES = [(backend, backend.split(".")[-1]) for backend in settings.AUTHENTICATION_BACKENDS[:-1]]
Please to make be define in `choices` enum. 🪨

2023-04-08 19:15 UTC, jathanism commented on nautobot/users/models.py
> +    _backend_name = models.CharField(max_length=100, editable=False)
Why prefix with `_`?

2023-04-08 19:15 UTC, jathanism commented on nautobot/users/models.py
> +SSO_CONFIG_TYPE_CHOICES = [("text", "Text"), ("secret", "Secret")]
Enum pls. 🙈

2023-05-11 12:21 UTC, bryanculver commented
Going to squash this into a prototype branch, it's a take at #2547 along with #2549.

Also easier facilitation of multiple SSO backends.

2023-05-11 12:21 UTC, merged