use pk as default lookup_field for NautobotUIViewSet
nautobot/nautobot pull request #3607
Opened 2023-04-18 14:41 UTC by timizuoebideri1

# Closes: #3497 
# What's Changed

# TODO

- [ ] Explanation of Change(s)
- [ ] Added change log fragment(s) (for more information see [the documentation](https://docs.nautobot.com/projects/core/en/stable/development/#creating-changelog-fragments))
- [ ] Attached Screenshots, Payload Example
- [ ] Unit, Integration Tests
- [ ] Documentation Updates (when adding/changing features)
- [ ] Example Plugin Updates (when adding/changing features)
- [ ] Outline Remaining Work, Constraints from Design

2023-04-18 20:27 UTC, jathanism approved these changes

2023-04-18 20:53 UTC, glennmatthews requested changes
There's text in `nautobot/docs/plugins/development.md` about `lookup_field` that needs to be updated appropriately for this change.

2023-04-18 20:53 UTC, glennmatthews commented on changes/3607.removed
> +Removed slug as the default lookup_field for NautobotUIViewSet making pk the default value.
```suggestion
Removed `"slug"` as the default `lookup_field` for `NautobotUIViewSet`, making `"pk"` now the default value.
```

2023-04-19 13:13 UTC, glennmatthews commented on nautobot/docs/plugins/development.md
````suggestion
```

+/- 2.0.0
    The default `lookup_field` for `NautobotUIViewSet` has been changed from `"slug"` to `"pk"`.
````

2023-04-19 13:37 UTC, glennmatthews commented on nautobot/docs/plugins/development.md
>  !!! note
```suggestion
    The default `lookup_field` for `NautobotUIViewSet` has been changed from `"slug"` to `"pk"`.

!!! note
```

2023-04-19 13:38 UTC, glennmatthews commented on nautobot/docs/plugins/development.md
>  !!! note
I think there's a bug in github's handling of suggested changes that include empty lines...

2023-04-21 17:09 UTC, merged