Update the pagination design and functionality in Nautobot 2.0 UI
nautobot/nautobot pull request #3966
Opened 2023-06-22 14:06 UTC by DistantVoyager

# Closes: #3904 <ISSUE NUMBER GOES HERE>
# What's Changed

- Restyled the pagination section.
- Added proper spacing/alignment to pagination section.
- Modified the back "<" and next ">" arrows to navigate to the previous/next page, respectively, rather than the first/last page.
- The back "<" and next ">" arrows no longer show when they aren't relevant (i.e. when on the first/last page).
- Added Input component for changing the page number, in addition to using the arrows.
- Added total number of rows to footer.

### New:

![image](https://github.com/nautobot/nautobot/assets/111259311/f3ec66b6-5428-4274-a9fe-5541da3e5f4a)

![image](https://github.com/nautobot/nautobot/assets/111259311/0be09d81-f5f4-4b85-91d2-50f501e3352f)

![image](https://github.com/nautobot/nautobot/assets/111259311/b58bf12b-fb0c-4d56-be39-4afaa310bd90)

![image](https://github.com/nautobot/nautobot/assets/111259311/38e0a202-62ab-404b-a643-48d814e2c2ac)

![image](https://github.com/nautobot/nautobot/assets/111259311/0775cfba-4030-49e4-93d3-75a3a32ffa12)

![image](https://github.com/nautobot/nautobot/assets/111259311/da805ff0-34b3-42e8-aaec-cd8be6ed8f62)

### Before:

![image](https://github.com/nautobot/nautobot/assets/111259311/06c91b31-2b57-43ce-bd0f-44798fef547e)

# TODO

- [x] Explanation of Change(s)
- [x] Added change log fragment(s) (for more information see [the documentation](https://docs.nautobot.com/projects/core/en/stable/development/#creating-changelog-fragments))
- [x] Attached Screenshots, Payload Example

2023-06-30 08:20 UTC, timizuoebideri1 commented on nautobot/ui/src/components/pagination.js
> +            )}
```suggestion
            {trueCurrentPage > firstPage && (
                <IconButton
                    onClick={() => onPageNumberChange("<")}
                    icon={<ChevronLeftIcon />}
                    color="gray-4"
                    variant="ghost"
                    pl="xs"
                    _hover={{
                        transform: "scale(1.2)",
                        color: "#007DFF",
                    }}
                />
            )}
```

2023-06-30 08:20 UTC, timizuoebideri1 commented on nautobot/ui/src/components/pagination.js
> +            )}
```suggestion
            {trueCurrentPage < lastPage && (
                <IconButton
                    onClick={() => onPageNumberChange(">")}
                    icon={<ChevronRightIcon />}
                    color="gray-4"
                    variant="ghost"
                    pr="xs"
                    _hover={{
                        transform: "scale(1.2)",
                        color: "#007DFF",
                    }}
                />
            )}
```

2023-06-30 08:20 UTC, timizuoebideri1 commented on nautobot/ui/src/components/pagination.js
> +                )}
When this is True, the page does not appear to be V center aligned; perhaps adjusting this to absolute will help.:
![Screenshot 2023-06-30 at 10 07 12 AM](https://github.com/nautobot/nautobot/assets/94907097/d1c8fae8-6da3-4d9d-893c-4edc29ca3d00)

2023-06-30 08:20 UTC, timizuoebideri1 commented on nautobot/ui/src/components/paginator.js
'paginator.js' and 'pagination.js' are quite similar and possibly misleading. 
Maybe create a 'Paginator' folder that contains all paginator-related components with better descriptive naming. just like in 'ObjectTable' or 'Retrieve', as well as consistency in component naming, i.e. Pagination.js instead of pagination.js.

2023-06-30 15:52 UTC, timizuoebideri1 approved these changes
If possible, make an index.js file in the Pagination subdirectory and export all relevant pagination components there.
Instead of imports llike this:
```js
import PageNumberForm from "@components/Pagination/PageNumberForm"
import PageSizeForm from "@components/Pagination/PageSizeForm"
import Pagination from "@components/Pagination/Pagination"
...
```

we do this

```js
import {PageSizeForm, PageNumberForm, Pagination } from "@components/Pagination"
```

2023-07-05 17:14 UTC, bryanculver requested changes

2023-07-05 17:14 UTC, bryanculver commented on nautobot/ui/src/components/Pagination/Pagination.js
> +class Pagination extends React.Component {
Why the class style component instead of the function style?

2023-07-05 17:14 UTC, bryanculver commented on nautobot/ui/package.json
> +        "@chakra-ui/icons": "^2.0.0",
Why did this change not incur an update to `package-lock.json`?

2023-07-05 17:14 UTC, bryanculver commented on changes/3904.changed
> +Added total number of rows to footer.
Please follow the `Added`, `Changed`, `Fixed`, `Removed` convention of files and sentence structure: https://docs.nautobot.com/projects/core/en/stable/release-notes/version-1.5/#v1521-2023-06-12

The file suffix let's Towncrier know which section it should live in.

2023-07-10 17:14 UTC, bryanculver approved these changes

2023-07-13 14:30 UTC, merged