resolves #342 issue with emitting null time_zone attr on Site object.
nautobot/nautobot pull request #419
Opened 2021-05-07 22:22 UTC by whitej6

### Fixes: #342

Issue initially appeared to be with the serializer field but on further investigation it was caused by the `timezone_field.fields.TimeZoneField._get_python_and_db_repr` returning None when expecting to return empty string.

2021-05-20 21:07 UTC, glennmatthews reviewed
Ignorant question - instead of overriding TimeZoneField with custom behavior, would it be as effective or more so to set `null=True` on the `Site.time_zone` field so that the API accepts None as valid instead?

2021-05-20 21:07 UTC, glennmatthews commented on nautobot/utilities/fields.py
> +        raise ValidationError("Invalid timezone '%s'" % value)
Is this pattern necessary for some reason? Or could we just:
```suggestion
            raise ValidationError("Invalid timezone '%s'" % value)
```

2021-05-24 15:50 UTC, jathanism commented
Per a discussion on Slack, [`django-timezone-field` already provides its own serializer field](https://github.com/mfogel/django-timezone-field/blob/master/timezone_field/rest_framework.py#L7), so we should try to see if we can make use of that and eliminate the bespoke one in the core.

2021-05-24 15:51 UTC, jathanism requested changes
See above comment! ☝️

2021-06-02 18:17 UTC, whitej6 commented on nautobot/dcim/tests/test_api.py
> +        # Attempt to create new site with valid time_zone attr.
@jathanism was opposed to this pattern, going to refactor this PR to see if the timezonefield from the upstream lib

2021-06-11 01:29 UTC, whitej6 commented
Tried swapping to the use of `timezone_field.rest_framework.TimeZoneSerializerField` for the serializer and still had the same result. To @glennmatthews's comment `allow_null=True` may be the cleaner way to account for this AND swapping to the prebuilt field vs custom code would be my vote.

2021-06-14 14:02 UTC, glennmatthews reviewed
@whitej6 Are you planning to rework this PR to use the prebuilt field + `allow_null=True`? Or are you proposing to move forward with the fix as currently implemented?

2021-06-14 14:02 UTC, glennmatthews commented on nautobot/utilities/fields.py
> +            raise ValidationError("Invalid timezone '%s'" % value)
```suggestion
            raise ValidationError(f"Invalid timezone '{value}'")
```

2021-06-14 14:04 UTC, whitej6 commented
@glennmatthews I am happy to rework this PR, would like to get a thumbs up from you and @jathanism prior to starting work.

2021-06-16 20:52 UTC, glennmatthews approved these changes

2021-06-16 20:52 UTC, glennmatthews commented on nautobot/dcim/tests/test_api.py
> +        Test non-null constraint to time_zone field on site.
Docstring seems no longer accurate.

2021-06-16 21:04 UTC, jathanism commented on nautobot/dcim/tests/test_api.py
> +        Test non-null constraint to time_zone field on site.
Oops. Thanks.

2021-06-18 00:07 UTC, jathanism approved these changes

2021-06-18 00:12 UTC, merged