Release v1.6.0-rc.1
nautobot/nautobot pull request #4203
Opened 2023-08-02 21:50 UTC by jathanism

# Closes: #<ISSUE NUMBER GOES HERE>
# What's Changed

Request to merge `develop` into `main` for Release `v1.6.0-rc.1`.

# TODO

- [ ] Explanation of Change(s)
- [ ] Added change log fragment(s) (for more information see [the documentation](https://docs.nautobot.com/projects/core/en/stable/development/#creating-changelog-fragments))
- [ ] Attached Screenshots, Payload Example
- [ ] Unit, Integration Tests
- [ ] Documentation Updates (when adding/changing features)
- [ ] Example Plugin Updates (when adding/changing features)
- [ ] Outline Remaining Work, Constraints from Design

2023-08-02 22:09 UTC, gsnider2195 approved these changes
That's a big release!

2023-08-02 23:44 UTC, HanlinMiao approved these changes

2023-08-03 02:27 UTC, bryanculver commented on pyproject.toml
> +version = "1.6.0-rc.1"
```toml
version = "1.6.0"
```

`main` should contain the releases, all others should contain pre-releases

2023-08-03 13:56 UTC, bryanculver requested changes
Let's wait until #4204

2023-08-03 15:44 UTC, glennmatthews commented on changes/4184.added
Need to rerun towncrier before merging this.

2023-08-03 19:04 UTC, closed without merging