U/jathanism develop to next 1.6.1
nautobot/nautobot pull request #4305
Opened 2023-08-22 21:06 UTC by jathanism

# Closes: #DNE
# What's Changed

Merge `develop` into `next` following Release v1.6.1.

# TODO

- [ ] Explanation of Change(s)
- [ ] Added change log fragment(s) (for more information see [the documentation](https://docs.nautobot.com/projects/core/en/stable/development/#creating-changelog-fragments))
- [ ] Attached Screenshots, Payload Example
- [ ] Unit, Integration Tests
- [ ] Documentation Updates (when adding/changing features)
- [ ] Example Plugin Updates (when adding/changing features)
- [ ] Outline Remaining Work, Constraints from Design

2023-08-22 21:19 UTC, glennmatthews commented on nautobot/extras/tests/test_datasources.py
> +            slug="repo-1",
repo slugs need to be python/graphql safe for `next`:

```suggestion
            slug="repo_1",
```

Same comment below.

2023-08-23 12:46 UTC, bryanculver requested changes

2023-08-23 12:46 UTC, bryanculver commented on nautobot/core/graphql/types.py
> +                    continue
Shouldn't this be using self.get_absolute_url?

2023-08-23 18:40 UTC, bryanculver approved these changes
🚀

2023-08-23 19:07 UTC, glennmatthews approved these changes

2023-08-23 23:58 UTC, merged