VDC: model & API
nautobot/nautobot pull request #6169
Opened 2024-08-30 06:49 UTC by timizuoebideri1

# Closes #<ISSUE NUMBER GOES HERE>
# What's Changed

# Screenshots

# TODO

- [ ] Explanation of Change(s)
- [ ] Added change log fragment(s) (for more information see [the documentation](https://docs.nautobot.com/projects/core/en/stable/development/#creating-changelog-fragments))
- [ ] Attached Screenshots, Payload Example
- [ ] Unit, Integration Tests
- [ ] Documentation Updates (when adding/changing features)
- [ ] Example App Updates (when adding/changing features)
- [ ] Outline Remaining Work, Constraints from Design

2024-08-30 20:45 UTC, HanlinMiao requested changes
We also need a manytomany relationship defined on Interface.

2024-08-30 20:45 UTC, HanlinMiao commented on nautobot/dcim/filters/__init__.py
> +from nautobot.dcim.models.device_components import VDC
I think it might be convention to declare `VDC` device/models/__init__.py and import VDC from there.

2024-08-30 20:45 UTC, HanlinMiao commented on nautobot/dcim/models/device_components.py
> +    description = models.TextField()
```suggestion
    description = forms.CharField(max_length=CHARFIELD_MAX_LENGTH, required=False)
```

2024-08-30 20:45 UTC, HanlinMiao commented on nautobot/dcim/models/device_components.py
> +        verbose_name="Primary IPv4 or IPv6",
Should we break this out to primary_ip4 and primary_ip6 just like Device?

2024-08-30 20:45 UTC, HanlinMiao commented on nautobot/dcim/models/device_components.py
> +    status = StatusField(blank=False, null=False)
We are missing an ID field here. Should be ID  = models.PositiveSmallIntegerField

2024-08-30 20:45 UTC, HanlinMiao commented on nautobot/dcim/models/device_components.py
> +class VDC(PrimaryModel):
This should be
```suggestion
class VirtualDeviceContext(PrimaryModel):
```

2024-09-03 13:32 UTC, timizuoebideri1 commented on nautobot/core/management/commands/generate_test_data.py
> +        st.content_types.add(ContentType.objects.get_for_model(VirtualDeviceContext))
remove;
after fix: No status exists for VDC model causing failing vdc factory initialisation

2024-09-05 19:02 UTC, glennmatthews commented on nautobot/dcim/tests/test_filters.py
> +        self.assertEqual(self.filterset(params, self.queryset).qs.count(), 1)
We should be using `assertQuerysetEqualAndNotEmpty` in these tests.

2024-09-09 06:26 UTC, timizuoebideri1 commented on nautobot/dcim/factory.py
> +    name = factory.Sequence(lambda n: f"VirtualDeviceContext {n}")
How do I archive this?

2024-09-09 12:48 UTC, glennmatthews commented on nautobot/dcim/factory.py
> +    name = factory.Sequence(lambda n: f"VirtualDeviceContext {n}")
Similar to `ModuleTypeFactory.model`, I think - but not blocking.

2024-09-09 12:50 UTC, glennmatthews commented on nautobot/core/constants.py
> +    "virtualdevicecontext",
IMO these should be searchable.

2024-09-09 12:50 UTC, glennmatthews commented on nautobot/extras/management/__init__.py
>      "dcim.Interface": dcim_choices.InterfaceStatusChoices,
Please keep in alphabetical order.

2024-09-12 14:45 UTC, glennmatthews commented on nautobot/dcim/models/devices.py
> +            return super().get_absolute_url(api)
```suggestion
    # TODO: Remove when UI View for this model is added
    def get_absolute_url(self, api=False):
        if api:
            return super().get_absolute_url(api=api)
        return None  # TODO
```

2024-09-12 19:32 UTC, timizuoebideri1 commented on nautobot/dcim/signals.py
> +    vdcs = kwargs["model"].objects.filter(pk__in=pk_set).exclude(device__in=[instance.device])
Yes, it's bidirectional. 
Confirmed using `nbshell`

2024-09-12 19:45 UTC, HanlinMiao approved these changes
LGTM if Glenn's comment is addressed

2024-09-12 19:47 UTC, glennmatthews commented on nautobot/dcim/models/device_components.py
> +    )
Fine if this is being done as a separate PR, let's just make sure we have a tracking issue open so it doesn't get lost in the shuffle.

2024-09-12 19:47 UTC, glennmatthews approved these changes

2024-09-12 20:04 UTC, timizuoebideri1 commented on nautobot/dcim/models/device_components.py
> +    )
https://github.com/nautobot/nautobot/issues/6211

2024-09-13 09:41 UTC, merged