Develop to next post 2.3.7
nautobot/nautobot pull request #6378
Opened 2024-10-16 20:05 UTC by HanlinMiao

2024-10-16 20:20 UTC, glennmatthews commented
Need to renumber some migrations again it looks like.

2024-10-16 20:36 UTC, glennmatthews requested changes

2024-10-16 20:36 UTC, glennmatthews commented on nautobot/extras/migrations/0119_fix_dynamic_group_group_type_data_migration.py
This is the wrong migration to renumber isn't it? Since it's in v2.3.7 already.

2024-10-16 21:02 UTC, glennmatthews approved these changes

2024-10-17 12:13 UTC, timizuoebideri1 approved these changes

2024-10-17 15:00 UTC, merged