Return `null/None` for GraphQL fields that require choices, but DB field is null.
nautobot/nautobot pull request #679
Opened 2021-07-13 02:47 UTC by FragmentedPacket

### Fixes: #466

This root of the issue is due to it not returning an appropriate choice when a field has `null=False` (default), `blank=True`, and choices defined. We now provide a `resolve_{field.name}` method that returns `null` on any fields that meet the conditions above.

This a known bug upstream in Graphene, but this puts in a workaround and more details can be found in the above issue.

If the fix is suitable, I will add tests.

2021-07-13 18:17 UTC, jathanism requested changes
This is fantastic! Can you please add a simple unit test to assert that this is in fact working somewhere in `nautobot.core.tests.test_graphql`? Thank you!

2021-07-14 15:16 UTC, jathanism approved these changes
This PR is a thing of beauty.

2021-07-14 15:25 UTC, glennmatthews approved these changes

2021-07-14 15:25 UTC, glennmatthews commented on nautobot/core/graphql/generators.py
> +    """Generate function to resolve fields that can be null, but blank=True, and choices defined.
I'm having trouble parsing this sentence. Maybe it accidentally a word?

2021-07-14 16:37 UTC, merged